services:

  mysql:
    image: mysql:8.0.33
    container_name: mysql_clean-arch
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_clean_arch
      MYSQL_ROOT_HOST: '%'
    command:
      - --default-authentication-plugin=mysql_native_password
      - --bind-address=0.0.0.0
      - --explicit_defaults_for_timestamp=1
      - --socket=/var/run/mysqld/mysqld.sock

    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql
    ports:
      - "3306:3306"
      - "50051:50051"
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq_clean-arch
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mysql_data:
  mysql_config:


networks:
  my-network:
    driver: bridge
