version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql_clean-arch
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_clean_arch
      MYSQL_USER: app_user
      MYSQL_PASSWORD: StrongDBPass123!
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d  # Scripts de inicialização
    ports:
      - "3306:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-proot", "--protocol=tcp"]
      interval: 10s
      timeout: 20s
      retries: 30
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    user: "999:999"
    container_name: rabbitmq_clean-arch
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - my-network
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl list_vhosts | grep -q /prod"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1G

  app:
    build: .
    container_name: app_clean-arch
    ports:
      - "4000:4000"    # GraphQL
      - "50051:50051"  # gRPC
      - "8000:8000"    # Health Check/API
    environment:
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: mysql_clean_arch
      DB_URL: "root:root@tcp(mysql:3306)/mysql_clean_arch?charset=utf8mb4&parseTime=True&loc=Local"
      RABBITMQ_URL: "amqp://admin:StrongPassword123!@rabbitmq:5672/prod?connection_timeout=30000&heartbeat=60"
      RABBITMQ_CONNECTION_TIMEOUT: 30000
      DEBUG: "true"
      LOG_LEVEL: "debug"
    networks:
      - my-network
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      start_period: 10s 
      retries: 15
    command: >
      sh -c "dockerize 
      -wait tcp://mysql:3306 
      -wait tcp://rabbitmq:5672 
      -wait http://rabbitmq:15672/api/vhosts/%2Fprod
      -timeout 300s 
      ./server start"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  grpc-web:
    image: fullstorydev/grpcui:latest
    command: 
      - "--plaintext"
      - "--bind=0.0.0.0:8081" 
      - "app_clean-arch:50051"  
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      app:
        condition: service_healthy

  evans:
    build:
      context: .
      dockerfile: Dockerfile.evans
    networks:
      - my-network
    depends_on:
      app:
        condition: service_healthy
    stdin_open: true 
    tty: true

volumes:
  mysql_data:
  mysql_run:
  rabbitmq_data:

networks:
  my-network:
    driver: bridge
