apiVersion: v1
kind: Service
metadata:
  name: serversvc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
